### ISSUE TITLE
Use of unresolved identifier 'logger'

### ISSUE THREAD

**Issue by grego360** [hrvolapeter/zetten#1]
Hi, 
It may be a noob mistake which I can't solve. In AuthenticationService Xcode presents an error "Use of unresolved identifier 'logger'". 
Any suggestions for a fix? 
Thank you

Very good explanation of the app on Medium. Thanks

<img width="1012" alt="Screenshot 2020-05-02 at 09 59 00" src="https://user-images.githubusercontent.com/15102782/80859857-b718f480-8c5b-11ea-9527-d3ab0cd7beb2.png">

**Comment by hrvolapeter** [comment]
Hi @grego360, sorry for the delay if you are still having the problem you can either just remove the logger event or most likely you are missing this file https://github.com/hrvolapeter/zetten/blob/master/zetten/Services/LoggingService.swift which defines the logger instance.

This is a bit ahead of the first part of tutorial but you've most likely copied the source code from master branch instead of `part-1` branch. Master contains the whole finished application.
