### ISSUE TITLE
Possible leak

### ISSUE THREAD

**Issue by adriansergheev** [hrvolapeter/zetten#2]
At launch there two instances of NoteListViewModel
<img width="232" alt="image" src="https://user-images.githubusercontent.com/23578783/81266680-777c4f00-9045-11ea-9c17-c20dfc395336.png">
and multiple instances of ViewModel created

<img width="216" alt="image" src="https://user-images.githubusercontent.com/23578783/81266852-ca560680-9045-11ea-99db-1c3c89110a4a.png">

probably related:
https://stackoverflow.com/questions/61636695/navigationlink-calling-destination-multiple-times

**Comment by hrvolapeter** [comment]
Hi @andriansergheev, a new View model is created for every note, those are Detail view models. SwiftUI is preloading possible buttons you can use so it has prepared detail views for some of your notes, this is handled by the list and navigation link combination. Navigation link is always preloaded, but list view performs some optimisations so that it doesn't always show all notes e.g notes behind fold.

However, the NoteListViewModel could be really a bug as there should be only one at a time and I'm not really able to replicate it, maybe if you could provides steps you performed after opening the app.
